# url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
# baseurl: "" # the subpath of your site, e.g. /blog
title: "Robert Rosas's Programming Portfolio" # the name of your site, e.g. ACME Corp.

collections:
  big_projects:
    output: true
  small_projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "big_projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "small_projects"
    values: 
      layout: "project"

theme: jekyll-theme-cayman